### PR TITLE
[release] merging crate-release-update into gh-pages

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @GuillaumeGomez @EPashkin @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
@GuillaumeGomez You don't know how generated "atk/auto/action.rs.html"?
It not present in my local `cargo doc --features "dox,embed-lgpl-docs"`
but current site also have both of it:
https://gtk-rs.org/docs/src/atk/auto/action.rs.html
https://gtk-rs.org/docs/atk/auto/action.rs.html

**Comment by GuillaumeGomez** [comment]
Absolutely no idea. I just run my release script on the `crate` branch which runs the same command you wrote...

**Comment by EPashkin** [comment]
Can you try run it locally on Linux?
I have only one "action.rs.html" but docs have 4 (second part from gio and don't builds locally when atk documenting).

**Comment by EPashkin** [comment]
also no link to non "src" version in current docs master.

**Comment by GuillaumeGomez** [comment]
Have you tested on the `crate` branch? (I insist on this one.) On the `crate` branch, there is only the `src/auto/action.rs`.

**Comment by EPashkin** [comment]
Both files same, maybe https://github.com/gtk-rs/release/blob/master/src/release.py#L366 produced duplicates?

**Comment by GuillaumeGomez** [comment]
Before executing this line, we run https://github.com/gtk-rs/release/blob/master/src/release.py#L337 which removes all files in case such thing would happen. ;)

**Comment by EPashkin** [comment]
> Have you tested on the crate branch? (I insist on this one.) On the crate branch, there is only the src/auto/action.rs.

Tested what? I don't run release script.
Also in atk only one `src/auto/action.rs` in master branch too.

**Comment by GuillaumeGomez** [comment]
I'll merge this PR meanwhile, it's still an improvement to the current situation.

**Pull request merged**
