### PR TITLE
[release] merging crate-release-update into gh-pages

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @GuillaumeGomez @EPashkin @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Once this one is merged, the release will be finally over! If there are objections, please state them now. ;)

**Comment by EPashkin** [comment]
@GuillaumeGomez You don't want publish  gtk-sys = "0.9.2" ?

**Comment by GuillaumeGomez** [comment]
Oh crap! Completely forgot about it. Good catch!

**Comment by GuillaumeGomez** [comment]
And done. Anything else @EPashkin ?

**Comment by EPashkin** [comment]
Seem https://github.com/gtk-rs/examples/pull/274 still not merged

**Comment by EPashkin** [comment]
and https://github.com/gtk-rs/gtk-rs.github.io/pull/132

**Comment by GuillaumeGomez** [comment]
The blog post will be last. Thanks a lot @EPashkin !

**Pull request merged**
