### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by EPashkin**
Not sure if all right

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Well, it's better than nothing, and if there are issues, we'll just see afterwards. Thanks!

**Comment by EPashkin** [comment]
Docs don't show features by default ?
I see 3.22 function but don't see that it feature gated http://gtk-rs.org/docs/gtk/struct.Clipboard.html#method.get_selection

**Comment by GuillaumeGomez** [comment]
It should. Can you open an issue on rustc and tag me on it please? So I can fix it quickly.

**Comment by EPashkin** [comment]
For http://gtk-rs.org/docs/gtk/struct.ActionBar.html it showed

**Comment by EPashkin** [comment]
Sorry I don't know what write.
For http://gtk-rs.org/docs/gtk/struct.ApplicationWindow.html I see feature for `get_id` but don't see for `get_help_overlay`. So maybe it don't shows if no docs.

**Comment by GuillaumeGomez** [comment]
Which is still an issue.

**Comment by GuillaumeGomez** [comment]
Ah, I think I got what you told. So it's a gir issue this time, not a rustdoc one. :)

**Pull request merged**
