### PR TITLE
[release] merging crate-release-update into gh-pages

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @GuillaumeGomez @EPashkin @sdroege

### CODE REVIEW

**Comment by EPashkin** [comment]
Thanks, 👍

**Comment by EPashkin** [comment]
Sorry, not fully '👍'
Can you check again why there both `gdk/enums/key/constant.A.html`  and `gdk/enums/key/constant.a.html` ?
This only repo with this behavior

**Comment by EPashkin** [comment]
Maybe one go from old version.

**Comment by sdroege** [comment]
:+1: except for what @EPashkin mentioned

**Comment by GuillaumeGomez** [comment]
We have both:

```Rust
pub const A: Key = ffi::GDK_KEY_A as u32;
pub const a: Key = ffi::GDK_KEY_a as u32;
```

And this goes on all letters (capital vs not capital).

**Comment by EPashkin** [comment]
@GuillaumeGomez Thanks for checking, so docs crate really untouchable on WINDOWS 😭

**Comment by GuillaumeGomez** [comment]
Welcome to NTFS. :D

**Pull request merged**
