### PR TITLE
Changed the example code in DrawingArea.html from C++ to Rust

### PR DESCRIPTION
**Pull request by SebastianMeinberger**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks for the PR, this is highly appreciated! However, this gets overwritten at each release so I'm not sure that merging it would make sense...

Any opinion @EPashkin @sdroege ?

**Comment by sdroege** [comment]
Merging like this would be useful then. I don't know what to do about that, this needs updates in the docs tooling first :)

**Comment by EPashkin** [comment]
IMHO https://github.com/gtk-rs/lgpl-docs/ need update instead:
From https://github.com/gtk-rs/lgpl-docs/blob/master/gtk/vendor.md make copy with same changes
from
`<!-- struct DrawingArea -->`
to (not including)
`<!-- impl DrawingArea::fn new -->`
and add it to https://github.com/gtk-rs/lgpl-docs/blob/master/gtk/docs.md
This way we get changes here on next doc update.

**Comment by SebastianMeinberger** [comment]
Ok, then I'm gonna add this to https://github.com/gtk-rs/lgpl-docs/blob/master/gtk/docs.md

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request closed without merging**
